# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47862073f5ff7cc48ed6f9fbd43b917a2cdf32dd998853468bb1d1b33afa7fd767104e0c2cb8e5918492d6d5ff0d8b8cfdc617c5779e284034188365407d44e2

test:
  secret_key_base: 7ad17064f95edab208aa859a0d611da956920f0bbf4c42a0838c6819061647f8adcdb6a4387d2330a8e7316cf5af2b182b417fc790307260633c482e23981b34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
